---
- name: "CentOS-7: Add EPEL repository"
  become: yes
  yum:
    state: present
    name: epel-release
    update_cache: yes
  tags: root

# The c compiler is required to build the twisted modules.
- name: "CentOS-7: Install python3 and gcc"
  become: yes
  yum:
    state: present
    name:
     - python3
     - make
     - gcc
  tags: root

- name: "CentOS-7: Install buildbot worker"
  become: yes
  pip:
    name: buildbot-worker
    virtualenv: /opt/buildbot-worker
    virtualenv_command: /usr/bin/python3 -m venv
  tags: root

- name: "CentOS-7: Set buildbot-worker path"
  set_fact:
    buildbot_worker_bin: /usr/bin/buildbot-worker

- name: "CentOS-7: Create buildbot-worker symlink"
  become: yes
  file:
    state: link
    src: /opt/buildbot-worker/bin/buildbot-worker
    path: "{{ buildbot_worker_bin }}"
  tags: root
