---
# The canonical hostname:
# ansible_host: openafs-prod-app-1.mit.edu
ansible_user: buildbot
afsbotcfg_master_python: "/opt/rh/rh-python36/root/usr/bin/python3.6"
afsbotcfg_sqlalchemy_version: "==1.4.28"
afsbotcfg_buildbot_version: "==3.5.0"
afsbotcfg_version: 25.10.7rc3

afsbotcfg_gerrit:
  url: "https://gerrit.openafs.org"
  ident: "gerrit"
  hostkey: "gerrit.hostkey"
  user: "buildbot"
  server: "gerrit.openafs.org"
  ssh_port: 29418
  ssh_keytypes: "+ssh-dss"

afsbotcfg_project:
  name: "openafs"
  title: "OpenAFS Buildbot"
  summary_title: "The OpenAFS Buildbot Coordinator"
  db_url: "sqlite:///state.sqlite"
  url: "https://buildbot.openafs.org/"
  www_port: 8011
  pb_port: 9989
  email_from: "buildbot@openafs.MIT.EDU"
  gitbaseurl: "https://gerrit.openafs.org"
  repo: "https://gerrit.openafs.org/openafs.git"
  start_delay: 10

  # Long term branch names.
  branches:
    dev: "master"
    stable: "openafs-stable-1_8_x"
    oldstable: "openafs-stable-1_6_x"

  # Nightly build times.
  nightly:
    dev: 1
    stable: 2
    oldstable: 3

  # Delete build logs older than four weeks on Sunday at 12:00PM (noon).
  janitor:
    log_horizon: 4
    day_of_week: 6
    hour: 12
