---
# ansible_host: openafs-prod-app-1.mit.edu
ansible_user: buildbot
buildbot_project: openafs
buildbot_master_have_sudo: no
buildbot_master_sqlalchemy_version: '==1.4.28'
buildbot_master_buildbot_version: '==3.5.0'
buildbot_master_python: "/opt/rh/rh-python36/root/usr/bin/python3.6"
buildbot_master_basedir: "/home/buildbot/master/openafs"
buildbot_master_gerrit_ident: gerrit
buildbot_master_gerrit_hostkey: gerrit.hostkey
buildbot_master_config_templates:
  - "{{ playbook_dir }}/files/master.cfg"
  - "{{ playbook_dir }}/files/forcegerritbuild.py"
  - "{{ playbook_dir }}/files/email_templates.py"
  - "{{ playbook_dir }}/files/passwords.ini"
  - "{{ playbook_dir }}/files/make-rpm-workspace.sh"
  - "{{ playbook_dir }}/files/unpack-dkms-rpm.sh"
afsbotcfg_title: "OpenAFS Buildbot"
afsbotcfg_summary_title: "The OpenAFS Buildbot Coordinator"
afsbotcfg_url: "https://buildbot.openafs.org/"
afsbotcfg_gerrit_url: "https://gerrit.openafs.org"
afsbotcfg_repo: "git://gerrit.openafs.org/openafs.git"
afsbotcfg_www_port: 8011
afsbotcfg_build_delay: 30

afsbotcfg_gerrit_server: "gerrit.openafs.org"
afsbotcfg_gerrit_ssh_port: 29418
afsbotcfg_gerrit_user: "buildbot"
afsbotcfg_gerrit_ident: gerrit
afsbotcfg_email_from: "buildbot@openafs.MIT.EDU"
afsbotcfg_notify_list:
  - "builders":
      - "linux-rc-x86_64"
    "recipients":
      - "mmeffie@sinenomine.net"
      - "mvitale@sinenomine.net"
      - "stephan_weisand@desy.de"
